### ISSUE TITLE
No module named 'gspread.ns'

### ISSUE THREAD

**Issue by LouisGerondeau** [robin900/gspread-dataframe#10]
Hi,

I'm geting this error message on :  
from gspread_dataframe import get_as_dataframe, set_with_dataframe

I'm using the latest gspread release (3.0.0) which doesn't seem to contain the ns module

**Comment by robin900** [comment]
gspread 3.0.0 uses only the v4 Sheets API, and it has been heavily refactored. I've opened #11 to represent the work to make gspread-dataframe support gspread >= 3.0.0.

In the meantime, I've released 2.1.1 which now specifies `gspread<3.0.0` as a requirement.  When #11 is complete, I'll make a major 3.0.0 release to represent non-backward-compatible support for gspread 3.0.0.

**Comment by robin900** [comment]
For now, are you required to use gspread 3.* in your project? If not, downgrade to gspread 2.1.1 and gspread-dataframe will work fine.

**Comment by LouisGerondeau** [comment]
That's what I've done !

**Comment by robin900** [comment]
@LouisGerondeau If you'd like to try it, I've added gspread 3.0.0 support in a gspread-dataframe 3.0.0 release that's now on PyPI. (gspread-dataframe 2.1.1 uses gspread 2; gspread-dataframe 3.0.0 uses gspread 3.)
