### ISSUE TITLE
TRUE/FALSE values become 1.0/0.0 when using get_as_dataframe()

### ISSUE THREAD

**Issue by chozelinek** [robin900/gspread-dataframe#15]
Hi there,

I'm trying to get the content of a GSheet as dataframe.

The GSheet contains something like:

v1 | v2 | v3
-- | -- | --
A | TRUE | FALSE
B | TRUE | FALSE
C | FALSE | TRUE
D | TRUE | TRUE

Then I get the worksheet loaded as in the tutorial:

```python
gsheet = gc.open_by_url(url)

worksheet = gsheet.worksheet("Sheet1")

df = get_as_dataframe(worksheet, parse_dates=True, header=0)
```

But the output shows no boolean (that's what I'd expect) but floats of 0.0 or 1.0.

v1 |	v2 | v3
---|---|---
A | 1.0 | 0.0
B | 1.0 | 0.0
C | 0.0 | 1.0
D | 1.0 | 1.0

Should I use pass some parameter to the function? Is there a solution to overcome this?

**Comment by chozelinek** [comment]
After playing a bit I've managed to get this code getting what I wanted, just for the record.

```python
gsheet = gc.open_by_url(url)

worksheet = gsheet.worksheet("Sheet1")

df = get_as_dataframe(worksheet, header=0, keep_default_na=False, true_values=[True])

df.replace('', np.nan, inplace=True)

df.dropna(axis='rows', how='all', inplace=True)
df.dropna(axis='columns', how='all', inplace=True)
```

**Comment by robin900** [comment]
Sorry for the very long delay in responding!

Yes, the solution is to convince TextParser to read those values as booleans, and I believe that it's as easy as passing `true_values=['TRUE'], false_values=['FALSE']` as extra keyword arguments to `get_as_dataframe`. If that is not sufficient, you might try passing `dtype={'v2': bool, 'v3': bool}` to provide a hint that those columns have a boolean datatype.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html
