### ISSUE TITLE
Deprecation warning due to invalid escape sequences in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [robin900/gspread-dataframe#17]
Deprecation warnings are raised due to invalid escape sequences in Python 3.8 . Below is a log of the warnings raised during compiling all the python files. Using raw strings or escaping them will fix this issue.

```
find . -iname '*.py'  | xargs -P 4 -I{} python -Wall -m py_compile {}

./gspread_dataframe.py:121: DeprecationWarning: invalid escape sequence \*
  """
```

**Comment by robin900** [comment]
Release 3.0.4 contains your merged fix, and is now on PyPI. Thanks for your submission!

**Comment by tirkarthi** [comment]
Thanks @robin900 :)
