### ISSUE TITLE
RFE: enable "prettyfing" on upload

### ISSUE THREAD

**Issue by sam-s** [robin900/gspread-dataframe#19]
It would be nice to be able to 
1. set column types (e.g., `%` or date, as well and the precision)
1. set column width (as when I double click on column border, it becomes as wide/narrow as necessary/sufficient)

**Comment by robin900** [comment]
Look at the [`gspread-formatting` package](https://github.com/robin900/gspread-formatting). In addition to core formatting operations, there is support for building one's own "dataframe formatter".

**Comment by robin900** [comment]
For setting column width or row height, you'll need to do a direct Sheets API call with an [UpdateDimensionPropertiesRequest](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/request#updatedimensionpropertiesrequest), which isn't yet supported by this package.

**Comment by robin900** [comment]
@sam-s I don't believe that I will be adding soon first-class support to gspread-formatting for row height/column width. If you really need the feature, look into the `Spreadsheet.batch_update` method in gspread; you can issue any amount of Sheets API requests and can provide an `updateDimensionProperties` request for each row or column that you want to set pixelSize for.

**Comment by robin900** [comment]
This issue had two parts -- set row/column size, and set date/number/etc. formatting. This issue also pertains to `gspread-formatting` and not to this package. The first part is covered by https://github.com/robin900/gspread-formatting/issues/10 and the second part is already provided by the `format_with_dataframe` function and `BasicFormatter` class in the `gspread_formatting.dataframe` module.  Closing this issue.
