### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jpmckinney** [robin900/gspread-dataframe#23]
I'm seeing the following error when trying to build documentation on ReadTheDocs for a package that depends on gspread-dataframe. I'm not sure what the issue is.

I can reproduce by running `python setup.py install --force` on this package: https://github.com/open-contracting/kingfisher-colab/blob/master/setup.py

```
Searching for gspread-dataframe
Reading https://pypi.python.org/simple/gspread-dataframe/
Downloading https://files.pythonhosted.org/packages/a5/60/274ba137f89b4cbbb3695a544a2ef48c64e7ab8072a0d3542f6cdb5d904d/gspread-dataframe-3.0.5.tar.gz#sha256=97170b36e2e92fa93102e6c73a19e2da1223eec6c11c08b48e3fdb56c3043790
Best match: gspread-dataframe 3.0.5
Processing gspread-dataframe-3.0.5.tar.gz
Writing /var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/easy_install-03z8zowc/gspread-dataframe-3.0.5/setup.cfg
Running gspread-dataframe-3.0.5/setup.py -q bdist_egg --dist-dir /var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/easy_install-03z8zowc/gspread-dataframe-3.0.5/egg-dist-tmp-8r41z5mh
error: [Errno 2] No such file or directory: '/var/folders/cs/3pnj707s581bjnsfv0wndqkh0000gn/T/easy_install-03z8zowc/gspread-dataframe-3.0.5/VERSION'
```

**Comment by robin900** [comment]
I've added a MANIFEST.in file to include the VERSION file in the sdist. New release 3.0.6 in PyPI contains this change. Tell me if that works! (Also, `gspread-formatting` suffered the same problem, and new release 0.2.2 has the same fix.)

**Comment by jpmckinney** [comment]
Thanks, works! https://pypi.org/project/check-manifest/ can help identify anything else to include.
