### ISSUE TITLE
Bug: escaping when allow_formulas = False is not returning any value

### ISSUE THREAD

**Issue by rstoki** [robin900/gspread-dataframe#34]
When the allow_formulas = False, and the DataFrame cell contains value like "=A", the code at line 88 tries to escape the value (to prepend apostrophe (') ), but this value is not returned from the function anywhere. So the return value is None. 

The problematic line: 
https://github.com/robin900/gspread-dataframe/blob/d1ec66dd7352992d922ed5093fd88992765d0418/gspread_dataframe.py#L88

The line should read: 
`return "'%s" % value`

**Comment by robin900** [comment]
@rstoki Thanks so much for submitting this bug issue. This use case managed to escape all my attempts at test coverage for all the string escaping secenarios!

I've added test coverage confirming your suggested fix. Release 3.1.3 with that fix is now present in PyPI for your use.
