### ISSUE TITLE
Cannot use gspread's add_row() method before using set_with_dataframe()

### ISSUE THREAD

**Issue by joleeTakeoff** [robin900/gspread-dataframe#39]
As a developer, I want to be able to add enough rows to the google spreadsheet with `gspread`'s `add_row()` method before using the function `set_with_dataframe()` with large datasets.

This might be due to here:
In the case that I don't want to resize,
https://github.com/robin900/gspread-dataframe/blob/master/gspread_dataframe.py#L282
 
which calls this function:
https://github.com/robin900/gspread-dataframe/blob/ee2aa14c5af04e0c7d1e909f434ae3e31839fe69/gspread_dataframe.py#L94

**Comment by robin900** [comment]
The code, when resize=False, is intended to achieve two objectives: 1) add only the rows and cols necessary to contain the dataframe being written; and 2) when the total cell count limit for a worksheet would be exceeded, trim cols or rows to the width or height of the dataframe to keep the cell count under the Sheets API limit.

What problem are your seeing, specifically, for your use case?

**Comment by joleeTakeoff** [comment]
This is the situation I am having:

If the code is in this format:

```
worksheet.add_rows(1000)
set_with_dataframe(worksheet, dataframe)
```

The 1000 rows that was added prior to `set_with_dataframe()` will be gone, and the worksheet might not have enough empty rows for `set_with_dataframe()` to dump the dataframe, such that error will be raised.

**Comment by robin900** [comment]
1) If you omit the call to `add_rows`, and instead just do:
```
set_with_dataframe(worksheet, dataframe)
```
...what happens?

2) What size, in columns and rows, is your dataframe?

**Comment by robin900** [comment]
And also 3) how many worksheets are in this Google spreadsheet? If you totalled up all the rows * cols of all the worksheets in the entire spreadsheet, would it be > 5 million? Because the 5 million cell limit is an API limit on the entire _spreadsheet_, not just a _single worksheet_. 

(The gspread-dataframe code does not attempt to learn the total cell count in the entire spreadsheet; instead it assumes that the cell limit is only for the worksheet in question. If there's a way to learn the entire spreadsheet's cell count without too many API calls, that might be a better approach.)

**Comment by joleeTakeoff** [comment]
1) if I omit the `add_rows()`, then eventually the Google Sheet would run out of available rows and raises an error like this:
`gspread.exceptions.APIError: {'code': 400, 'message': 'Range (MFC_ABS3116!A1367:E1747) exceeds grid limits. Max rows: 1366, max columns: 27', 'status': 'INVALID_ARGUMENT'}`

2) on average the size in rows are ~450 rows, and the columns is constantly at 8 columns

3) The number of worksheets is 2 to 3 work sheets, but I don't foresee the total rows go over 5 million

**Comment by robin900** [comment]
So you're writing a dataframe of 450 rows x 8 columns to a worksheet that by default, when it's created, already has 1000 rows and 26 columns? What is the row count and column count of the worksheet before your code runs?

The gspread-dataframe code, when resize=False, does ensure a minimum column or row count to contain the dataframe contents. It does so via the gspread method `worksheet.resize()`, which works well in all the test cases and avoids the "grid limits exceeded" error that you're seeing. 

I'm very very puzzled here, but would very much like to help. Would you be willing to post your _entire_ Python script/code, and also the version of gspread-dataframe and version of gspread and version of Phython you are using?

**Comment by robin900** [comment]
@joleeTakeoff Are you still seeing trouble with your code? If so, can you provide the information I mentioned above, because I'd love to help. If not, can you confirm that you're no longer seeing trouble using this package, and I can close this issue?

**Comment by joleeTakeoff** [comment]
Please close this, thank you!
