### ISSUE TITLE
Consider allowing option to drop duplicates in set_with_dataframe

### ISSUE THREAD

**Issue by MrBeardedGuy** [robin900/gspread-dataframe#41]
Consider this scenario where worksheet and dataframe have duplicated data: 
```
	Worksheet				Dataframe 			
								
0	a0	b0	c0			b0	c0	d0
1	a1	b1	c1			b1	c1	d1
```

Would it be possible to add an option to eliminate the duplicated values (in this case `b0, c0, b1, c1`) when uploading the data with `set_with_dataframe`?

**Comment by robin900** [comment]
I do not understand what behavior you desire. Are you saying that you would like to skip over two columns of the dataframe when writing to the worksheet? But also somehow skipping over two columns in the worksheet so that those two columns in the sheet are unaffected by the dataframe cells being written?

**Comment by robin900** [comment]
Just guessing here, but if you only wish to write some column or columns of a dataframe to a worksheet, derive a second dataframe that contains just the column or columns to write; then use parameters for `set_as_dataframe` that allow you to offset the column, etc.:

```
def set_with_dataframe(
    worksheet,
    dataframe,
    row=1,
    col=1,
    include_index=False,
    include_column_header=True,
    resize=False,
    allow_formulas=True,
    string_escaping="default"):
```

**Comment by MrBeardedGuy** [comment]
My bad. Too little description :)  
I'm thinking of a scenario where a dataframe gets appended to a worksheet with some data in it. The action might result in duplicated cols or rows that need to be dropped (impossible to predict which ones though). 

Appending can be easily done by passing the option `row=last_row_of_sheet_data+1` to the `set_with_dataframe ` 

I was wondering if `set_with_dataframe` could have an option to remove the duplicated values in case the worksheet already has some data. Similar to what [Panda's drop duplicates does.](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html)
