### ISSUE TITLE
No module named 'gspread'

### ISSUE THREAD

**Issue by Atulsah** [robin900/gspread-dataframe#49]
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from pprint import pprint

class GoogleSheet():

	scope = ["https://spreadsheets.google.com/feeds",'https://www.googleapis.com/auth/spreadsheets',"https://www.googleapis.com/auth/drive.file","https://www.googleapis.com/auth/drive"]
	#creds = ServiceAccountCredentials.from_json_keyfile_name("creds.json", scope)
	creds = gspread.service_account()
	#client = gspread.authorize(creds)

	sh = creds.open("DI ITEM SHEET")  # Open the spreadhseet
	wks = sh.worksheet("2022-APR") # Open the workhseet

	data = wks.get_all_records()

this file runs successfully  when run direct on the console 

but give an error: No module named 'gspread' on server

**Comment by robin900** [comment]
Probably the gspread package is not installed on the server you are using.
