### ISSUE TITLE
get_as_dataframe() is reading the whole sheet data

### ISSUE THREAD

**Issue by GmGniap** [robin900/gspread-dataframe#59]
Most of the cases , Google spreadsheet has 1000 rows in one tab as default. I tried to read all the tabs inside the spreadsheet and it got gspread API Error saying ""Quota exceeded for quota metric 'Read requests' and limit 'Read requests per minute per user' of service 'sheets.googleapis.com' .... ".

When I tried to print the shape of dataframes for each tab , it's showing `(999, <col_num>)`. So, it looks like `get_as_dataframe()` is taking the whole sheet rows including the blank lines. I tried to use options - `skip_blank_lines` from this [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) that mentioned in [here](https://pypi.org/project/gspread-dataframe/). But it didn't work.

My temporary solution is setting `skipfooter` to `900` because luckily all of my tabs had maximum 100 rows. But I felt like there should be more better solution in case we can't guess max rows in each tab.

![Screenshot 2024-02-20 at 7 09 24 PM](https://github.com/robin900/gspread-dataframe/assets/20846286/15c8dece-811d-4f2c-be78-b04d7149c4a4)

**Comment by robin900** [comment]
@GmGniap Another issue has been filed related to this, and I'm going to test myself the efficacy of `skip_blank_lines`, because that should totally work, and it would be upsetting if it didn't.

**Comment by robin900** [comment]
Aha, I see -- `skip_blank_lines` merely skips lines that are _completely_ blank; any line with any CSV field separators but all blank values, such as `,,,,,`, will not be considered blank and will not be skipped.

It seems the correct approach, for now, is to use the DataFrame's `dropna` method, which is reliable and has many configurable options. One `dropna` call can drop columns with all blank values; a second `dropna` call can drop rows with all blank values:

```
dataframe = get_as_dataframe(...)
dataframe = dataframe.dropna(axis=0, how='all')  # now free of empty rows
dataframe = dataframe.dropna(axis=1, how='all')  # now free of empty columns
```
