### ISSUE TITLE
get dataframe does not work with non-programatically created sheets

### ISSUE THREAD

**Issue by xiao-wevnal** [robin900/gspread-dataframe#61]
if get dataframe does not provide an option to remove empty rows and columns(which needless to say are added by default when you create a spreadsheet in google drive) at the end, it is easier to just do

```
rows = worksheet.get_all_values()
df = pd.DataFrame(rows[1:], columns=rows[0])
```

I kinda want to try and see what this library is about but its such a bad taste in the mouth that the first thing you'd want to do when working on a real spreadsheet you have lying around is to skip what it provides.

**Comment by robin900** [comment]
To skip empty rows: `skip_blank_lines=True`. All the options to `pandas.read_csv` are accepted by get_as_dataframe().

To skip empty columns, there isn't a read_csv option that performs this work. Instead, with the returned data frame, `dataframe.dropna('all', axis=1)` will produce a dataframe free of any column that had only blank values.

**Comment by pytlv** [comment]
I also find it preferable that empty rows and columns should be ignored.
Regarding your comment, behavior should be: 
 "only drop blank columns with a blank header as well".
This behavior is consistent with google sheets add filter, which treats table with a consecutive header row.

**Comment by xiao-wevnal** [comment]
> Further findings:
> 
> * `skip_blank_lines=True` only removes lines from CSV input that are completely blank, without any field separator characters. Lines with only blank values but with valid field separators, such as `,,,,,,`, are not skipped.
> * We can discuss including non-pandas keywords arguments to `get_as_dataframe`; feel free to contribute your thoughts directly to this discussion thread.
> * In the meantime, there is a straightforward and reliable solution via the `DataFrame.dropna` method. One `dropna` call can drop columns with all blank values; a second `dropna` call can drop rows with all blank values:
> 
> ```
> dataframe = get_as_dataframe(...)
> dataframe = dataframe.dropna(axis=0, how='all')  # now free of empty rows
> dataframe = dataframe.dropna(axis=1, how='all')  # now free of empty columns
> ```

Thanks for the promptly reply and advice! 
Lemme take some time to test everything you've suggested along with what i had in mind and get back to you.

**Comment by robin900** [comment]
@xiao-wevnal I have implemented the feature, both new parameters are True by default (`drop_empty_rows`, `drop_empty_columns`), unit and integration tests are in place, and it will bein release 4.0.0 in PyPI shortly.

**Comment by xiao-wevnal** [comment]
Thanks! Sorry I wasn't able to get to you in time, I'll remember to take a look at this new feature from gspread-dataframe when i got to work on the spreadsheet program again
