### ISSUE TITLE
...object has no attribute...

### ISSUE THREAD

**Issue by mmergola** [robin900/gspread-dataframe#9]
I might be in the wrong spot for this, but I keep getting the following error:

AttributeError: 'Client' object has no attribute 'get_cells_feed'

This happens whenever I try to write to my Google Spreadsheet using any DataFrame.

Sometimes it happens in the resize_to_minimum function, and other times it happens in the _get_all_values function, but I believe it errors as soon as it tries to read the client.worksheet.

**Comment by robin900** [comment]
Please post the version of gspread you’re using. I may need to support a changed gspread API...

**Comment by robin900** [comment]
@mmergola My package is not yet compatible with the just-released gspread 3.0.0. Are you required to use gspread 3.* in your project? If not, downgrade to gspread 2.1.1 and gspread-dataframe will work fine.

I'm going to cut a bugfix release that clarifies a dependency on `gspread<3.0.0`. And I've opened #11 to represent the migration of gspread-dataframe to support only gspread 3.0.0 and higher.

**Comment by robin900** [comment]
@mmergola If you'd like to try it, I've added gspread 3.0.0 support in a gspread-dataframe 3.0.0 release that's now on PyPI. (gspread-dataframe 2.1.1 uses gspread 2; gspread-dataframe 3.0.0 uses gspread 3.)
